### PR TITLE
fix: improve table layout

### LINKED ISSUE #102: Improve on display for Council category breakdown
Improving on the back of issue #35 can we improve the styling on the table display in https://opendata.scot/analytics/local-authority-categories/?

- whitespace around the table so it doesn't spread end to end
- reduce fontsize (to allow margins)
- fixed width columns
- change colour paletter to single gradient instead of red/green

### PR DESCRIPTION
**Pull request by fozy81**
## Description
This fixes issue https://github.com/OpenDataScotland/the_od_bods/issues/102

## Motivation and Context

- [x]     fixed width columns
- [x]    change colour paletter to single gradient instead of red/green

Other suggeted fixes:
- [ ]    whitespace around the table so it doesn't spread end to end
- [ ]     reduce fontsize (to allow margins)

## How Has This Been Tested?

Tested locally. No units test (selenium etc written).

## Screenshots (if appropriate):

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by JackGilmore** [comment]
Looks good. Would maybe suggest taking off the `text-orientation: sideways` property as it doesn't look to have any effect and I don't think it's compatible with many browsers: https://caniuse.com/mdn-css_properties_text-orientation_sideways

**Comment by fozy81** [comment]
I've switched to red gradient and flipped the text the other way and removed the text-orientation: sideways. Let me know if any more suggestions.

**Comment by JackGilmore** [comment]
Just looking at this and `writing-mode: sideways-lr` only seems to be supported by Firefox at the moment 😢 https://caniuse.com/mdn-css_properties_writing-mode_sideways_values.

You could maybe try wrapping the text in a span and then setting the following styles on the span?
```css
writing-mode: vertical-lr;
transform: rotate(180deg);
```

**Comment by fozy81** [comment]
Hi @JackGilmore - thanks for catching this, I'm testing on firefox. I've updated to use rotate. So much for web standards...why can't everyone just use firefox :smiley_cat:

**Comment by JackGilmore** [comment]
@fozy81 Looks great. Cheers for the contribution Tim!

**Pull request merged**
