### PR TITLE
Update angus.md

### PR DESCRIPTION
**Pull request by Saipranoy**
Added the wdtk_id for angus, argyll and Bute 
## Description

They both are health and social care so i copied the ids from WDTK website
## Motivation and Context

Trying to help in fixing this issue https://github.com/OpenDataScotland/the_od_bods/issues/71

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by JackGilmore** [comment]
Thanks for your contribution and welcome @Saipranoy. I can see your PR description mentions Argyll and Bute but I can only see a change for Angus HSCP. Are you missing a commit?

**Comment by Saipranoy** [comment]
I thought with one PR multiple commits can be pushed. Looks like I need to do for each commit. I'll do that.

**Comment by JackGilmore** [comment]
You should be able to push multiple commits to the same PR. What Git client/setup are you using?

**Comment by Saipranoy** [comment]
Im using general github website.

**Comment by JackGilmore** [comment]
You should be able to make further changes and commit them to your forked branch (https://github.com/Saipranoy/jkan/tree/patch-1) to bundle them together for one pull request.

If you're still unsure, I would recommend checking out GitHub's guide to contributing to projects: https://docs.github.com/en/get-started/quickstart/contributing-to-projects?tool=webui

**Comment by JackGilmore** [comment]
Hi @Saipranoy. Just wondering if you're still wanting to add in the ID for Argyll and Bute as part of this pull request or if you'd rather I just merged this one for now?

**Comment by Saipranoy** [comment]
ill merge this one for now.

**Pull request merged**
